version: "2"

run:
  timeout: 5m
  tests: true
linters:
  enable:
    - govet
    - staticcheck
    - ineffassign
    - revive
    - unused
    - misspell
    - gocyclo
    - revive
    - errcheck
issues:
  max-issues-per-linter: 0
  max-same-issues: 0